### PR TITLE
delete SPLASHES variable when it is kept in the memory and wastes it

### PR DESCRIPTION
**Pull request by leha-code**

### CODE REVIEW

**Review by Alvarito050506 — APPROVED** [review]

**Comment by leha-code** [comment]
WHY SO SLOW.exe

**Comment by mobilegmYT** [comment]
I'll go force merge

**Review by TheBrokenRail — CHANGES_REQUESTED** [review]
Is there any reason to actually merge this? This only saves 732 *bytes*. This is not going to affect performance and/or memory usage in any way detectable.

**Comment by leha-code** [comment]
Thats for the future.

**Comment by leha-code** [comment]
Why do yu guys keep deleting me from the org?

**Comment by leha-code** [comment]
Reopen whenyou will adda lot splashes.

**Comment by TheBrokenRail** [comment]
> Thats for the future.

If we had 4000 splashes, each 25 characters each, it would *only* take up 1 MB. Still pointless.

**Comment by leha-code** [comment]
Oops accident

**Pull request closed without merging**
